/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-secondary-fixed": "#191b26",
        "on-primary-fixed": "#19114b",
        "text-primary": "#FFFFFF",
        "error-container": "#93000a",
        "surface-container-high": "#2a292e",
        "on-primary-fixed-variant": "#463f79",
        "on-surface-variant": "#c9c5d1",
        "outline-variant": "#47454f",
        "inverse-on-surface": "#313034",
        "on-error-container": "#ffdad6",
        "hover-glow": "rgba(143, 136, 199, 0.35)",
        "secondary": "#c5c5d4",
        "on-secondary": "#2e303b",
        "inverse-surface": "#e5e1e7",
        "tertiary": "#d9c76c",
        "on-tertiary-container": "#4a3f00",
        "surface-tint": "#c7bfff",
        "surface-container": "#201f23",
        "navbar-bg": "rgba(10, 10, 15, 0.65)",
        "tertiary-fixed-dim": "#d9c76c",
        "primary-container": "#9089c8",
        "on-primary": "#2f2861",
        "on-secondary-fixed-variant": "#454652",
        "primary-fixed-dim": "#c7bfff",
        "on-secondary-container": "#b7b7c6",
        "tertiary-fixed": "#f6e385",
        "on-surface": "#e5e1e7",
        "on-error": "#690005",
        "inverse-primary": "#5d5792",
        "outline": "#928f9a",
        "surface-variant": "#353439",
        "tertiary-container": "#bdac54",
        "surface-container-low": "#1c1b1f",
        "text-secondary": "#B8B8C7",
        "on-primary-container": "#282159",
        "surface": "#141317",
        "surface-bright": "#3a383d",
        "background": "#0B0B12",
        "border-glass": "rgba(255, 255, 255, 0.12)",
        "on-tertiary": "#383000",
        "on-tertiary-fixed-variant": "#524700",
        "surface-container-lowest": "#0e0e12",
        "secondary-container": "#474855",
        "surface-dim": "#141317",
        "surface-container-highest": "#353439",
        "surface-glass": "rgba(255, 255, 255, 0.08)",
        "primary": "#c7bfff",
        "on-background": "#e5e1e7",
        "on-tertiary-fixed": "#211b00",
        "error": "#ffb4ab",
        "secondary-fixed-dim": "#c5c5d4",
        "secondary-fixed": "#e2e1f1",
        "primary-fixed": "#e4dfff"
      },
      "spacing": {
        "margin-x": "48px",
        "gutter": "24px",
        "container-max": "1440px",
        "section-gap": "64px",
        "header-height": "72px"
      },
      "fontFamily": {
        "display-lg": ["Montserrat"],
        "headline-md": ["Montserrat"],
        "body-md": ["Inter"],
        "title-lg": ["Inter"],
        "headline-lg": ["Montserrat"],
        "label-md": ["Inter"],
        "display-md": ["Montserrat"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"]
      },
      "fontSize": {
        "display-lg": ["56px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "title-lg": ["20px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "1.25", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "display-md": ["40px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}